### ISSUE TITLE
Run example.go for to long

### ISSUE THREAD

**Issue by NetWilliam** [matryer/moq#29] opened 2017-08-14 06:46 UTC
I've been through two examples. one of them are going well, which is described in the blog. But another has met some error.
I've downloaded the example.go in github and used command `go get github.com/matryer/moq && go generate` as the preview example. However it seemed like not going to finish. Perhaps a dead loop?

and my screen shot as follow:

![moq_error](https://user-images.githubusercontent.com/3966971/29260822-cecc187a-80fe-11e7-8771-74dd5e75871c.png)

**Comment by alioygur** [comment] 2017-09-09 21:50
+1

**Comment by matryer** [comment] 2017-09-21 17:33
eh!?! Can you guys reproduce this in a unit test?

**Comment by toreolsensan** [comment] 2017-10-09 19:47
I think I ran into the same issue when I tried running moq with no GOPATH variable set.

I'm not currently prepared to submit a fix for this, but found that in importer.go vendorPath() ends up in an endless loop checking for packages in "/". This is caused by isGopath() never returning false because gopaths() only checks for the GOPATH environment variable and returns an empty list.

The gopaths() function should probably add a default $HOME/go entry, which is where the go tooling says is the default.

A workaround is to export GOPATH=$HOME/go.

**Comment by adimarco** [comment] 2017-11-22 15:03
Like @toreolsensan  said, this seems to be `moq` not knowing how to fall back to the default GOPATH when none is explicitly set, though it does work correctly as long as `moq` doesn't have to go looking for anything outside your current package.  

To reproduce, run `unset GOPATH` and try to run moq for a primitive interface (e.g., the one from the moq documentation):
```
package foo

//go:generate moq -out myinterface_moq_test.go . MyInterface

type MyInterface interface {
     Method1() error
     Method2(i int)
}
```

Run `go generate` and everything works fine.  The desired code is generated.

Change that interface to use an outside package, e.g.:
```
package foo

import (
       "net/http"
)
//go:generate moq -out myinterface_moq_test.go . MyInterface

type MyInterface interface {
     Method1(w http.ResponseWriter) error
     Method2(i int)
}
```

Run `go generate` and it hangs forever.

Then set your GOPATH properly `export GOPATH=$HOME/go`.  Run `go generate` again and everything works fine.

**Comment by sudo-suhas** [comment] 2020-08-01 05:01
I tried running the steps which were mentioned and this is what I am seeing:

```
$ go generate ./...
go/format: 35:35: missing ',' in parameter list (and 10 more errors)
moq [flags] source-dir interface [interface2 [interface3 [...]]]
  -fmt string
    	go pretty-printer: gofmt (default) or goimports
  -out string
    	output file (default stdout)
  -pkg string
    	package name (default will infer)
Specifying an alias for the mock is also supported with the format 'interface:alias'
Ex: moq -pkg different . MyInterface:MyMock
pkg/moq/testpackages/gogenvendoring/user/user.go:5: running "moq": exit status 1
```

Closing as stale.

**Closed by sudo-suhas** 2020-08-01 05:01 UTC
